import React, { useState, useEffect } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ScoreGrid from '../components/ScoreGrid'
import SignupForm from '../components/Form/SignupForm'

const courseUrl = 'http://localhost:8000/api/course/'
const getCourses = () => {
  fetch(courseUrl)
    .then(response => response.json())
    .then(data => console.log(data));
}

const postCourse = () => {
  const data = {
    name: 'my 3000 course',
    lat: -20.88644,
    lng: 163.19727,
  }

  // Default options are marked with *
  fetch(courseUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });
}

const Home: NextPage = () => {

  useEffect(() => {
    // get all the courses!!
    getCourses();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Disco Fever 🥏 🤒 🥳 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ScoreGrid />
        test
        <SignupForm />
        <button onClick={() => postCourse()}>click mee</button>
      </main>

    </div>
  )
}

export default Home
