# Generated by Django 4.0.4 on 2022-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_golfhole_options_golfhole_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcard',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
