# Generated by Django 4.0.4 on 2022-05-19 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_golfcard_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfhole',
            name='hole_number',
        ),
        migrations.AddField(
            model_name='holescore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
