version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: ./config/django/Dockerfile
    command: gunicorn --workers 3 disco_fever.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/usr/src/app
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - web
