version: '3.8'

services:
  nextjs:
    build:
      context: ../
      dockerfile: ./config/nextjs/Dockerfile
    command: yarn dev
    volumes:
      - ../:/usr/src/app
    expose:
      - 3000

  web:
    build:
      context: ../
      dockerfile: ./config/django/Dockerfile
    command: gunicorn --workers 3 disco_fever.wsgi:application --bind 0.0.0.0:8000  --reload
    volumes:
      - ../:/usr/src/app
    env_file:
      - ./.env.dev
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ../:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=disco_fever_user
      - POSTGRES_PASSWORD=disco_fever_password
      - POSTGRES_DB=disco_fever_dev
volumes:
  postgres_data:
