name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.4.2
        
      - name: Build Frontend
        run: cd my-app && yarn install && yarn build
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: 'will-be-added-in-next-step'

      - name: Add known host
        run: ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
        
      - name: Copy Files
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: -avz
            REMOTE_HOST: ${{ secrets.HOST_IP }}
            REMOTE_USER: root
            TARGET: /root/disco-app/disco-fever/
            EXCLUDE: .git/
            
      - name: Restart Server
        uses: arthurvanl/action-exec-ssh@v2.0.7
        with:
           host: ${{ secrets.HOST_IP }}
           username: root
           commands: systemctl restart gunicorn
