name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.4.2
        
      - name: Cache Frontend Assets
        uses: actions/cache@v3
        with:
          path: my-app
          key: ${{ runner.os }}-{{ hashFiles('my-app/yarn.lock') }}
          
      - name: Build Frontend
        run: cd my-app && yarn install && yarn build
        
  deploy:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: -avz
          REMOTE_HOST: ${{ secrets.HOST_IP }}
          REMOTE_USER: root
          TARGET: /root/disco-app/disco-fever/
          EXCLUDE: .git/

      - name: Build and Restart Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST_IP }}
          username: root
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /root/disco-app/disco-fever
            ./config/scripts/deploy.sh
